// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: presence.proto

package presence

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PresenceServiceClient is the client API for PresenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PresenceServiceClient interface {
	UpdatePresence(ctx context.Context, in *UpdatePresenceRequest, opts ...grpc.CallOption) (*UpdatePresenceResponse, error)
	GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...grpc.CallOption) (*GetPresenceResponse, error)
	StreamPresence(ctx context.Context, in *StreamPresenceRequest, opts ...grpc.CallOption) (PresenceService_StreamPresenceClient, error)
}

type presenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPresenceServiceClient(cc grpc.ClientConnInterface) PresenceServiceClient {
	return &presenceServiceClient{cc}
}

func (c *presenceServiceClient) UpdatePresence(ctx context.Context, in *UpdatePresenceRequest, opts ...grpc.CallOption) (*UpdatePresenceResponse, error) {
	out := new(UpdatePresenceResponse)
	err := c.cc.Invoke(ctx, "/presence.PresenceService/UpdatePresence", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) GetPresence(ctx context.Context, in *GetPresenceRequest, opts ...grpc.CallOption) (*GetPresenceResponse, error) {
	out := new(GetPresenceResponse)
	err := c.cc.Invoke(ctx, "/presence.PresenceService/GetPresence", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) StreamPresence(ctx context.Context, in *StreamPresenceRequest, opts ...grpc.CallOption) (PresenceService_StreamPresenceClient, error) {
	stream, err := c.cc.NewStream(ctx, &PresenceService_ServiceDesc.Streams[0], "/presence.PresenceService/StreamPresence", opts...)
	if err != nil {
		return nil, err
	}
	x := &presenceServiceStreamPresenceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PresenceService_StreamPresenceClient interface {
	Recv() (*PresenceUpdate, error)
	grpc.ClientStream
}

type presenceServiceStreamPresenceClient struct {
	grpc.ClientStream
}

func (x *presenceServiceStreamPresenceClient) Recv() (*PresenceUpdate, error) {
	m := new(PresenceUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PresenceServiceServer is the server API for PresenceService service.
// All implementations must embed UnimplementedPresenceServiceServer
// for forward compatibility
type PresenceServiceServer interface {
	UpdatePresence(context.Context, *UpdatePresenceRequest) (*UpdatePresenceResponse, error)
	GetPresence(context.Context, *GetPresenceRequest) (*GetPresenceResponse, error)
	StreamPresence(*StreamPresenceRequest, PresenceService_StreamPresenceServer) error
	mustEmbedUnimplementedPresenceServiceServer()
}

// UnimplementedPresenceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPresenceServiceServer struct {
}

func (UnimplementedPresenceServiceServer) UpdatePresence(context.Context, *UpdatePresenceRequest) (*UpdatePresenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePresence not implemented")
}
func (UnimplementedPresenceServiceServer) GetPresence(context.Context, *GetPresenceRequest) (*GetPresenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPresence not implemented")
}
func (UnimplementedPresenceServiceServer) StreamPresence(*StreamPresenceRequest, PresenceService_StreamPresenceServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPresence not implemented")
}
func (UnimplementedPresenceServiceServer) mustEmbedUnimplementedPresenceServiceServer() {}

// UnsafePresenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PresenceServiceServer will
// result in compilation errors.
type UnsafePresenceServiceServer interface {
	mustEmbedUnimplementedPresenceServiceServer()
}

func RegisterPresenceServiceServer(s grpc.ServiceRegistrar, srv PresenceServiceServer) {
	s.RegisterService(&PresenceService_ServiceDesc, srv)
}

func _PresenceService_UpdatePresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).UpdatePresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/presence.PresenceService/UpdatePresence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).UpdatePresence(ctx, req.(*UpdatePresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_GetPresence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).GetPresence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/presence.PresenceService/GetPresence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).GetPresence(ctx, req.(*GetPresenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_StreamPresence_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPresenceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PresenceServiceServer).StreamPresence(m, &presenceServiceStreamPresenceServer{stream})
}

type PresenceService_StreamPresenceServer interface {
	Send(*PresenceUpdate) error
	grpc.ServerStream
}

type presenceServiceStreamPresenceServer struct {
	grpc.ServerStream
}

func (x *presenceServiceStreamPresenceServer) Send(m *PresenceUpdate) error {
	return x.ServerStream.SendMsg(m)
}

// PresenceService_ServiceDesc is the grpc.ServiceDesc for PresenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PresenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "presence.PresenceService",
	HandlerType: (*PresenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePresence",
			Handler:    _PresenceService_UpdatePresence_Handler,
		},
		{
			MethodName: "GetPresence",
			Handler:    _PresenceService_GetPresence_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPresence",
			Handler:       _PresenceService_StreamPresence_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "presence.proto",
}
